### PR TITLE
limited message to 1000

### PR DESCRIPTION
**Pull request by ighmaZ**
solved #18 limited message to 1000

### CODE REVIEW

**Comment by jeremyckahn** [comment]
Thank you @ighmaZ! #18 specifies a limit of 10,000 characters, but that's a simple tweak. I can take it from here.

**Comment by jeremyckahn** [comment]
This work has been deployed. Thank you again @ighmaZ!

**Comment by ighmaZ** [comment]
My pleasure! Would love to work on more issues

**Comment by jeremyckahn** [comment]
@ighmaZ Awesome! If you're interested, #6 might be a good feature to work on next.

**Pull request merged**
