### PR TITLE
Added Disclaimer

### PR DESCRIPTION
**Pull request by MohammadTaseenKhan**

### CODE REVIEW

**Comment by jeremyckahn** [comment]
Great idea to add this. Thank you @MohammadTaseenKhan! I'd like to make and push a few edits to this, and then I'll follow up with you to make sure you think it looks good.

**Comment by jeremyckahn** [comment]
@MohammadTaseenKhan I reworded the disclaimer in https://github.com/MohammadTaseenKhan/chitchatter/commit/1f010e9cdac3b2afb8ce65e61bfcbbdc5a86d066. What do you think of the new wording?

**Comment by jeremyckahn** [comment]
Regarding the content in `disclaimer.html`, I think it's worth integrating with the more fully with the app. What do you think about moving this content to the About page (see: https://github.com/jeremyckahn/chitchatter/blob/develop/src/pages/About/About.tsx)?

I've got a few thoughts about the content itself, but let's wait until we've found a more integrated home for it before changing the language.

**Comment by MohammadTaseenKhan** [comment]
> Regarding the content in `disclaimer.html`, I think it's worth integrating with the more fully with the app. What do you think about moving this content to the About page (see: https://github.com/jeremyckahn/chitchatter/blob/develop/src/pages/About/About.tsx)?
> 
> I've got a few thoughts about the content itself, but let's wait until we've found a more integrated home for it before changing the language.

You may change it to the about section but due to much content in one page might cause a user to not get interested to read it

We need to make it into a separate page because it is a legal info which will fight for us the developers against the fraud users.

But you can write a summary or direct simple sentence in to about section so that the users can understand that whatever they will do, it will be their consequences

**Comment by jeremyckahn** [comment]
> You may change it to the about section but due to much content in one page might cause a user to not get interested to read it
> 
> We need to make it into a separate page because it is a legal info which will fight for us the developers against the fraud users.

That makes sense. I'd be okay with adding a new route within the app for just the Disclaimer (similarly to how we have it for the About page). I'd just like to avoid having a standalone HTML file for this content.

> But you can write a summary or direct simple sentence in to about section

I think that would be be an excellent addition to the Disclaimer route described above!

**Comment by MohammadTaseenKhan** [comment]
# yes sure 

And the HTML file was created to show the format of the Disclaimer

**Pull request closed without merging**
