### PR TITLE
added new useEffect

### PR DESCRIPTION
**Pull request by ighmaZ**
hi @jeremyckahn ! heres the new branch

### CODE REVIEW

**Comment by jeremyckahn** [comment]
Thanks for sharing your progress @ighmaZ! This seems to be showing a test notification for me:

Notification screenshot

I'm using Firefox on Linux. Are you not seeing a similar notification in your environment?

**Comment by ighmaZ** [comment]
@jeremyckahn ! Don't know why its not showing on my brave browser running on mac

**Comment by jeremyckahn** [comment]
> @jeremyckahn ! Don't know why its not showing on my brave browser running on mac

It seems to be working on Brave for my Linux environment as well. You may need to manually give the page notification permission:

Brave screenshot

**Comment by ighmaZ** [comment]
i have already given but dont know why its not showing

**Comment by jeremyckahn** [comment]
> i have already given but dont know why its not showing

That's strange. What happens in other browsers like Firefox or Chrome?

**Comment by ighmaZ** [comment]
not showing there too, i dont know why

**Comment by jeremyckahn** [comment]
Very strange. Maybe there's some operating system-level settings that's preventing browser notifications from showing?

As a last resort, you could trying running your branch in a virtual machine for a totally fresh environment. Beyond that, I'm not sure what to suggest. Do you want to keep working on this issue, or perhaps pick up a different one?

**Comment by ighmaZ** [comment]
@jeremyckahn , i would love to pick another issue

**Comment by jeremyckahn** [comment]
@ighmaZ got it. I'll close this PR and unassign the issue. Let me know if there's something else you'd like to work on!

**Pull request closed without merging**
